//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""TowerDefence"",
            ""id"": ""c24a0007-dfac-4101-b3b4-1066d01f5d5a"",
            ""actions"": [
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""55478120-d2f7-4323-bdf6-4bdbfffa4a61"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""f0a42c2f-17ec-4059-bf08-f2ec469f6abb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bf3e2efe-7587-4a02-a1b4-37c1f9dfa64f"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23c6f9e1-efc3-47ae-a82a-61c2c46e462e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TowerDefence
        m_TowerDefence = asset.FindActionMap("TowerDefence", throwIfNotFound: true);
        m_TowerDefence_MousePosition = m_TowerDefence.FindAction("MousePosition", throwIfNotFound: true);
        m_TowerDefence_LeftClick = m_TowerDefence.FindAction("LeftClick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TowerDefence
    private readonly InputActionMap m_TowerDefence;
    private ITowerDefenceActions m_TowerDefenceActionsCallbackInterface;
    private readonly InputAction m_TowerDefence_MousePosition;
    private readonly InputAction m_TowerDefence_LeftClick;
    public struct TowerDefenceActions
    {
        private @PlayerActions m_Wrapper;
        public TowerDefenceActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MousePosition => m_Wrapper.m_TowerDefence_MousePosition;
        public InputAction @LeftClick => m_Wrapper.m_TowerDefence_LeftClick;
        public InputActionMap Get() { return m_Wrapper.m_TowerDefence; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TowerDefenceActions set) { return set.Get(); }
        public void SetCallbacks(ITowerDefenceActions instance)
        {
            if (m_Wrapper.m_TowerDefenceActionsCallbackInterface != null)
            {
                @MousePosition.started -= m_Wrapper.m_TowerDefenceActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_TowerDefenceActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_TowerDefenceActionsCallbackInterface.OnMousePosition;
                @LeftClick.started -= m_Wrapper.m_TowerDefenceActionsCallbackInterface.OnLeftClick;
                @LeftClick.performed -= m_Wrapper.m_TowerDefenceActionsCallbackInterface.OnLeftClick;
                @LeftClick.canceled -= m_Wrapper.m_TowerDefenceActionsCallbackInterface.OnLeftClick;
            }
            m_Wrapper.m_TowerDefenceActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @LeftClick.started += instance.OnLeftClick;
                @LeftClick.performed += instance.OnLeftClick;
                @LeftClick.canceled += instance.OnLeftClick;
            }
        }
    }
    public TowerDefenceActions @TowerDefence => new TowerDefenceActions(this);
    public interface ITowerDefenceActions
    {
        void OnMousePosition(InputAction.CallbackContext context);
        void OnLeftClick(InputAction.CallbackContext context);
    }
}
